name: jasamarga_inspeksi
description: "Aplikasi inspeksi kendaraan untuk Jasamarga"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  http: ^1.1.0
  pdf: ^3.10.4
  printing: ^5.11.0
  intl: ^0.18.1
  syncfusion_flutter_pdf: ^24.2.9
  shared_preferences: ^2.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  excel: ^2.1.0
  csv: ^5.0.2
  image_picker: ^1.0.4
  geolocator: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/logo_jjc.png
    - assets/onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_jjc.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_jjc.png
  android: true
  ios: true
  web: false
  image_dark: assets/logo_jjc.png
