name: jasamarga_inspeksi
description: "Aplikasi inspeksi kendaraan untuk Jasamarga"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.0
  http: ^1.2.2
  pdf: ^3.11.3
  printing: ^5.13.5
  intl: ^0.19.0
  syncfusion_flutter_pdf: ^24.2.9
  shared_preferences: ^2.3.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  excel: ^4.0.6
  csv: ^6.0.0
  image_picker: ^1.1.2
  geolocator: ^10.1.0
  open_file: ^3.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/logo_jjc.png
    - assets/onboard1.png
    - assets/onboard2.png
    - assets/onboard3.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_jjc.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo_jjc.png
  android: true
  ios: true
  web: false
  image_dark: assets/logo_jjc.png
